# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
import os


WORKFLOW_NAME="Divergence time estimation"

configfile: "config/config.yaml"

from snakemake.utils import min_version
min_version("8.14") 

#include: "rules/setup.smk"

VCF = config["vcf"] ## only bi-allelic SNPS
FASTA = config["fasta"]
GFF = config ["gff"]
SUBSET = config["subset"] # subset of sample names to extract

onsuccess:
    print( WORKFLOW_NAME+" finished, no error")
    shell("send_message.py '" + WORKFLOW_NAME + " finished, no error'") # comment out this line if you don't have a messenger script
onerror:
    print("An error occurred, see the log")
    shell("send_message.py 'An error occured in " + WORKFLOW_NAME + ", see the log: {log}'")
    
onstart:    
    print ("----------------------------------------------------------------------------")
    print ("Starting " + WORKFLOW_NAME)   
    print ("----------------------------------------------------------------------------")
    shell ('send_message.py "' + WORKFLOW_NAME + ' started at $(date)"') # comment out this line if you don't have a messenger script


rule all:
    input: 
        m="results/pairwise-differences.txt",
        T1="results/divergence-time-mu1.txt",
        T2="results/divergence-time-mu2.txt",
         s1="results/summary-mu1.txt",
        s2="results/summary-mu2.txt"
    message: "Pairwise difference are found in {input.m}.\n Divergence time estimates are in {input.T1} and {input.T2}. "

rule degenotate:
    conda:"envs/degenotate.yaml"
    input:
        fasta=FASTA,
        gff=GFF
    output:
        "results/degenotate/4Xsites.bed"
    message: "calculating 4-fold degerate sites"
    shell:
        r"""
        degenotate.py -a {input.gff}  -g {input.fasta} -x 4 -d " " -o $(dirname {output})  --overwrite
        cat $(dirname {output})/degeneracy-all-sites.bed | awk '$5 == 4{{print($0)}}' > {output}
        echo Found $(wc -l {output}) sites.
        """

rule rename_chromosomes:
    conda: "envs/vcftools.yaml"
    input: vcf=VCF,
           namemap="config/"+config["renamechr"]
    output: vcf="results/renamed.vcf.gz",
            idx="results/renamed.vcf.gz.csi"
    threads: 60
    message: "Renaming chromosomes using namemap {input.namemap}"         
    shell:
        r"""
        bcftools annotate --threads {threads} --rename-chrs {input.namemap} {input.vcf} | bgzip > {output.vcf}
        bcftools index -f {output.vcf}
        echo "---------------------------------------------------------"
        echo "Remaining markers after {rule}:"
        bcftools stats {output.vcf} | grep -e"^SN"
        
        """        

        
rule index_vcf:
    conda:"envs/vcftools.yaml"
    input:
        vcf=VCF,
    output: VCF+".csi"
    message: "Indexing input VCF"
    shell:
        r"""
         bcftools index -f {input.vcf}
        """
            


        
rule filter_vcf:
    conda:"envs/vcftools.yaml"
    input:
        vcf=VCF if not config["renamechr"] else "results/renamed.vcf.gz",
        vcfindex=VCF+".csi" if not config["renamechr"] else "results/renamed.vcf.gz.csi",
        sites="results/degenotate/4Xsites.bed",
    output: "results/filtered-4X.vcf.gz"
    threads: 40
    message: "Filtering SNP matrix"
    threads: 60
    shell:
        r"""
        bcftools view --threads {threads} --regions-file {input.sites} \
        -m2 -M2 -v snps --output-type z  --output-file {output} {input.vcf}
        bcftools index {output}
        #bcftools view --threads {threads} -R {input.sites} --with-header --types snps --max-alleles 2  {input.vcf} |\
        #vcftools --gzvcf - --max-missing 1 --recode --stdout | bgzip -c > {output}
        #bcftools index {output}
        echo "---------------------------------------------------------"
        echo "Remaining markers after filtering for 4X-degenerate sites:"
        bcftools stats {output} | grep -e"^SN"
        """
        
rule make_genotype_matrix:
    conda:"envs/vcftools.yaml"
    
    input: "results/filtered-4X.vcf.gz"
    output: "results/genotype-matrix.txt"       
    threads:40
    params: subset=SUBSET
    message: "generating Genotype matrix"
    shell:
        r"""
         echo "{params.subset}" | tr ',' '\t' > {output} # create simple header
         echo "" >> {output}
         # get the genotype matrix, we don't need the separator
         bcftools query -s "{params.subset}" -f '[%GT\t]\n' {input} | tr -d '/|' | sed -E s/\\t$// | sed s/10/01/ >> {output} 


        """
            
rule difference_matrix:
    conda: "envs/r-proxy.yaml"
    input:
        gmat="results/genotype-matrix.txt",
        sites="results/degenotate/4Xsites.bed",
        clust="config/samples.clust"
    output:
        diffmat="results/pairwise-differences.txt",
        T1="results/divergence-time-mu1.txt",
        T2="results/divergence-time-mu2.txt",
        G1="results/divergence-generations-mu1.txt",
        G2="results/divergence-generations-mu2.txt",
        s1="results/groupwise-summary-mu1.txt",
        s2="results/groupwise-summary-mu2.txt",
        html="results/report.html"
    log: "logs/R-diff.log"
    threads: 120    
    params:       
        mu1="1.84e-10",
        mu2="1.67e-10",
        G=2920 # generations per year (Peter et al.)         
    shell:
        r"""
        cat <<'EOF' > {rule}.$$.tmp.R
        library(proxy)
        library(dplyr)
        library(parallelDist)
        library(kableExtra)
        
        G <- {params.G}
        N <- nrow(read.delim(file="{input.sites}")) ## how many total sites are there
        cat(paste("Using",N,"as number of total 4D sites\n"))

        
        ## Attempt to use multi-threads to speed up distance matrix calculation
        # this is too slow for large matrices
        # mydist <- function(x,y) sum(future_apply((cbind(x,y)),1, comp2))
        # but effectively, that is the same as:
         mydist <- function(x,y) sum(x+y==11, na.rm=TRUE)
        
        gm <- read.delim(file="{input.gmat}", header=T, colClasses="numeric", na.strings=c("..","."))
        cat("read genotypes, calculating distance matrix\n")
        # gm <- t(gm==11) # convert into binary matrix (Hom_ALT | REF)
        # gm[is.na(gm)] <- FALSE
         m <- as.matrix(proxy::dist(t(gm), method=mydist))
        # m <- as.matrix(parDist(gm, method = 'manhattan', threads={threads}))
        # this doesn't treat NA properly
        # m <- as.matrix(dist(gm, method = 'manhattan'))
        # the number of different positions of two binary vector is equal to the manhattan distance
        # not the 'binary' distance
        cat ('got distance matrix of size: ')
        cat(paste(object.size(m), "\n"))
        write.table(m, file="{output.diffmat}", sep="\t", quote = F)
        d.jc <- -3/4 * log(1 - ((4/3)*(m/N)))
        ## Calculate generations
        G1 <- (d.jc/{params.mu1})
        G2 <- (d.jc/{params.mu2})
        ## Calculate time
        T1 <- (d.jc/{params.mu1})/G
        T2 <- (d.jc/{params.mu2})/G
        write.table(T1, file="{output.G1}", sep="\t", quote = F)
        write.table(T2, file="{output.G2}", sep="\t", quote = F)
        write.table(T1, file="{output.T1}", sep="\t", quote = F)
        write.table(T2, file="{output.T2}", sep="\t", quote = F)

        ## calculate group averages
        clust <- read.delim(file="{input.clust}", header = FALSE) ## group file
        clust[,1] <-make.names(clust[,1]) # fix names to match distance matrix
        if (length(setdiff(colnames(T1),clust[,1])) > 0) {{
            cat ("The following sample names were not found in your cluster file. Make sure, your cluster file contains all sample names ")
            print( setdiff(colnames(T1),clust[,1]) )
        }}    
        stopifnot(length(setdiff(colnames(T1),clust[,1])) == 0) # not all colnames found in cluster file
        clust <- merge(colnames(T1), clust, by=1, all=F, sort=F) ## match with the table headers
        groups <- clust[,ncol(clust)]
        xi <- rep(groups, nrow(T1))
        yi <- as.vector(sapply(groups, rep, nrow(T1)))
        bgroups <- apply(cbind(xi, yi), 1, function(x) paste0(sort(x), collapse = "-"))
        inds <- - seq(1, ncol(T1)^2, ncol(T1)+1) # remove diag from estimates
        gdist1 <- data.frame(dist=as.vector(matrix(as.matrix(T1), ncol=1, byrow = T)), 
            generations=as.vector(matrix(as.matrix(G1), ncol=1, byrow = T)), 
            group=bgroups)[inds,]
        gdist2 <- data.frame(dist=as.vector(matrix(as.matrix(T2), ncol=1, byrow = T)), 
            generations=as.vector(matrix(as.matrix(G2), ncol=1, byrow = T)), 
            group=bgroups)[inds,]

        get.q95 <- function(x) {{
         q <- quantile(x = x, c(0.025,0.975))
         paste0('[',round(q[1],3),',',round(q[2],3),']' )
        }}

        
        res1 <- gdist1 %>% group_by(group) %>% 
           summarise(mean_time=mean(dist), median_time=median(dist), sd_time=sd(dist),
           min=min(dist), max=max(dist), "95%conf"=get.q95(dist), 
           median_generations=format(median(generations), scientific = T), N=length(dist))
        res2 <- gdist2 %>% group_by(group) %>% 
           summarise(mean_time=mean(dist), median_time=median(dist), sd_time=sd(dist),
           min=min(dist), max=max(dist), "95%conf"=get.q95(dist), 
           median_generations=format(median(generations), scientific = T), N=length(dist))
        write.table(res1, file="{output.s1}", sep="\t", quote = F)
        write.table(res2, file="{output.s2}", sep="\t", quote = F)
        
        # generate some user-readable output and HTML report
        kable(res1, caption=paste("mu =", "{params.mu1}"))
        kable(res2, caption=paste("mu =", "{params.mu2}"))

        cat("<html>\n  <head>\n   <title>Divergence time report</title> </head>\n  <body>\n", file='{output.html}', append=FALSE)
        
        cat(kable(
           t(data.frame(
           'Total number of 4XD sites'=N,
           'Total number of samples'=ncol(gm),
           'Total number of genotyping markers'=nrow(gm),
           'Generations/year'=G,
           'mu1'="{params.mu1}",
           'mu2'="{params.mu2}"
        )),
        format = 'html', caption = "Analysis parameters:"), file='{output.html}', append=TRUE)
        
        cat(kable(res1, caption=paste("mu1 =", "{params.mu1}"), format='html'), file='{output.html}', append=TRUE)
        cat(kable(res2, caption=paste("mu1 =", "{params.mu2}"), format='html'), file='{output.html}', append=TRUE)
        cat("  </body>\n</html>", file='{output.html}', append=TRUE)
        
        
EOF
        
        Rscript {rule}.$$.tmp.R > {log} 2>&1
        rm {rule}.$$.tmp.R        
        """
